[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "myproj"
version = "1.0.0"
requires-python = ">=3.9"

[tool.setuptools]
package-dir = {"" = "src"}
